Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    [Table("pizza")]
    public class Pizza
    {
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        public float Price { get; set; }

        public Pizza(string name, string description, string image, float price)
        {
            this.Name = name;
            this.Description = description;
            this.Image = image;
            this.Price = price;
        }

    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {

        public List<Pizza> getPizze()
        {
            List<Pizza> pizzeList = new()
            {
                new Pizza("Margherita", "pomodoro, mozzarella", "/img/pizza1.png", 10.99F ),
                new Pizza("Marinara", "pomodoro, aglio rosmarino", "/img/pizza2.png", 7.99F),
                new Pizza("Lombarda", "pomodoro, mozzarella, carciofi, grana", "/img/pizza3.png", 11.99F),
                new Pizza("Pugliese", "pomodoro, mozzarella, capperi, aciughe", "/img/pizza4.png", 10.99F)

            };
            return pizzeList;
        }

        public IActionResult Index()
        {
            return View("Home");
        }
        public IActionResult Pizze()
        {
           
            return View("Index", getPizze());
        }

        public IActionResult Show(int id)
        {
            return View(getPizze()[id]);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Pizza/Home.cshtml
@{
    Layout = "Guest/_Layout";
}
    
  <div class="container debug text-center">
      <h1 class="mb-3">Benvenuto!</h1>
      <p>It has survived not only five centuries, but also the leap into electronic typesetting, 
          remaining essentially unchanged. It was popularised in the 1960s with the release of
          Letraset sheets containing Lorem Ipsum passages
          , and more recently with desktop publishing software like Aldus PageMaker including 
          versions of Lorem Ipsum.
      </p>
  </div>

Views/Pizza/Index.cshtml
@{
    @model List<Pizza>;

    Layout = "Guest/_Layout";
}
    
    <h2 class="mb-3">Menu</h2>
    <div class="pizza-container container">
        <div class="row">
            @for (var i = 0; i < Model.Count; i++)
            {
                <div class="col-4 p-2 mb-3">
                    
                     <div class="px-1 py-3 debug">
                        <h3>@Model[i].Name</h3>
                            <img src="@Model[i].Image" class="mb-2"/>

                            <h6>Euro: @Model[i].Price</h6>
                            <p>@Model[i].Description</p>
                            <a class="btn_show px-3 py-2 rounded-pill" href="@Url.Action("Show", "Pizza", new{Id = i})">View more</a>    
                    </div> 
                    
                </div>
                
            }
           
        </div>
    </div>

Views/Pizza/Show.cshtml
@{
    @model Pizza;

    Layout = "Guest/_Layout";
}
    <div class="container debug px-3 py-4 bg-beige">
        <div class="row">
            <div class="col-6">
                <img src="@Model.Image" class="mb-2 w-100 rounded-box"/>
            </div>
             <div class="col-6">
                 <h2 class="mb-3">@Model.Name</h2>
                 <p>@Model.Name</p>
                 <p>@Model.Description</p>
            </div>
        </div>
       
    
    </div>

Views/Shared/Guest/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>

     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" 
     integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==
    " crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        @Html.Partial("Partials/_Header");

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        @Html.Partial("Partials/_Footer");

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/Partials/_Footer.cshtml
<div class="container">
    &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
</div>

Views/Shared/Partials/_Header.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dudi pizze</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                 <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Home</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Pizze">Pizze</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Privacy">Privacy</a>
                </li>

            </ul>
        </div>
    </div>
</nav>